tap "homebrew/bundle"
brew "awscli"
brew "bat"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "gnupg"
brew "hyperfine"
brew "imagemagick"
brew "jq"
brew "lsd"
brew "mas"
brew "mise"
brew "monolith"
brew "neovim"
brew "ripgrep"
brew "sheldon"
brew "sops"
brew "tokei"
brew "vim"
brew "wget"
brew "xh"
brew "zoxide"
cask "alacritty"
cask "appcleaner"
cask "arc"
cask "aws-vault"
cask "blackhole-2ch"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox"
cask "firefox@developer-edition"
cask "google-chrome"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "obs"
cask "raycast"
cask "safari-technology-preview"
cask "slack"
cask "sublime-text"
cask "tableplus"
cask "the-unarchiver"
cask "trex"
cask "visual-studio-code"
cask "vivaldi"
cask "wezterm"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "CompareMerge2", id: 1459748650
mas "Disk Speed Test", id: 425264550
mas "FileZilla Pro", id: 1298486723
mas "Xcode", id: 497799835
