tap "homebrew/bundle"
brew "ffmpeg"
brew "git"
brew "imagemagick"
brew "mas"
brew "mise"
brew "wget"
cask "android-studio"
cask "appcleaner"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "microsoft-teams"
cask "obs"
cask "raycast"
cask "safari-technology-preview"
cask "slack"
cask "sublime-text"
cask "tableplus"
cask "the-unarchiver"
cask "visual-studio-code"
cask "warp"
cask "wezterm"
cask "zoom"
mas "Amphetamine", id: 937984704
mas "Blackmagic Disk Speed Test", id: 425264550
mas "CompareMerge2", id: 1459748650
mas "FileZilla Pro - FTP and Cloud", id: 1298486723
mas "Xcode", id: 497799835
