# history
# HISTFILE="$XDG_STATE_HOME"/zsh/history
# HISTSIZE=10000
# SAVEHIST=10000

setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
